Payment Type Controller & Test
NewForce-at-Mountwest/bangazon-api-radvioli pull request #5
Opened 2019-05-21 16:00 UTC by nikx1015

# Description

Created payment type controller which allows the user to create, edit, and delete payment types. I also created a test to make sure the controller is allowing the user to get a single payment type, get all payment types, create a payment type, edit a payment type, and delete a payment type.

## Related Ticket(s)

## Steps to Test
Pull this branch down from Github and open the Bangazon API project in Visual Studio. Right click on BangazonTestAPI and choose to option to run tests to confirm the api is working as expected. 

# Checklist:
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new errors
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2019-05-21 18:01 UTC, BatsGoScreechh commented
Everything looks good to me. Code is well commented. Tests came back all green and running the server returned the expected result! :+1:

2019-05-21 19:27 UTC, ColonelSped commented
Please add the ticket information.

2019-05-22 12:44 UTC, ColonelSped requested changes

2019-05-22 12:44 UTC, ColonelSped commented on BangazonAPI/TestBangazonAPI/TestBangazonAPI.csproj
>  </Project>
Overall code looks good!

2019-05-22 13:26 UTC, ColonelSped commented
Please use this as a model for your "Steps to Test

git add and git commit whatever you're working on on your branch
git checkout master to switch to your local master branch
git fetch --all will give you access to your teammate's branches (if they've pushed them up)
git checkout <your-teammate's-branch-name> to switch to their branch
If you don't see the most recent version of their files, try git pull origin <your-teammate's-branch-name>
Run your server on their branch and make sure everything looks okay
Once server is running, use your browser to navigate to api/products to ensure that correct information is displayed.

Afterwards, in Visual Studio, go to the TestProduct.cs file under TestBangazonAPI and right-click on it and click on Run Tests. Ensure that all tests come back green.

Check verbiage and comments to make sure they are legible and understandable.

2019-05-22 14:21 UTC, ColonelSped approved these changes

2019-05-22 14:21 UTC, ColonelSped commented
Please merge

2019-05-22 14:22 UTC, merged